function setup_nl()

% Runs the installation procedure with nl_nl as default language.

%--------------------------------------------------------------------------
% Etienne Gaudrain <etienne.gaudrain@cnrs.fr> - 2018-05-02
% CNRS UMR 5292, FR | University of Groningen, UMCG, NL
%--------------------------------------------------------------------------

fprintf('First select the SOURCE folder.\nThis is the (Google Drive) folder that contains the master code of PICKA. It should be called "PICKA Experiments".\n(Press Enter to continue)\n\n');
pause();

src = uigetdir(fullfile(getHome(), 'Google Drive'), 'PICKA installation: Source directory (Google Drive)');

if src(1)==0
    error('No source folder was selected');
end

fprintf('Source folder: %s\n\n', src);

fprintf('Then select the DESTINATION folder.\nNo new "PICKA Experiments" folder will be created. All the code will be installed directly in the selected folder.\n');
fprintf('This is where you will be running your experiments from.\n(Press Enter to continue)\n\n');
pause();

dst = uigetdir(pwd(),'PICKA installation: Destination directory');

if dst(1)==0
    error('No destination folder was selected');
end

fprintf('Destination folder: %s\n\n', dst);

fprintf('Are you sure you want to install from the source to the destination folder?\n');
r = input('yes | no: ', 's');

r = lower(r(1));

switch r
    case 'y'
        if ~exist('manage_picka.py', 'file')
            py_code = base64decode(payload());
            f = fopen('manage_picka.py', 'w');
            fwrite(f,py_code);
            fclose(f);
        end
        %[c, ~] = system(sprintf('python ./manage_picka.py install "%s" "%s"', src, dst), '-echo');
        mod = py.importlib.import_module('manage_picka');
        py.reload(mod);
        fprintf('\n\n');
        success = py.manage_picka.main(py.list({'install', src, dst, 'nl_nl'}));
        if success==0
            try
                delete('manage_picka.p*', 'setup_nl.m');
            catch
            end
        end
        
    otherwise
        fprintf('\nInstallation aborted.\n');
end

%------------------------------------------
function home = getHome()
% return the path to the home folder indepently of OS (e.g. works in Linux,
% apple, and windows)
 
if ispc
    home = fullfile(getenv('HOMEDRIVE'), getenv('HOMEPATH'));
else
    home = getenv('HOME');
end

%------------------------------------------
function y = base64decode(x)

x = uint8(x(:));

base64 = org.apache.commons.codec.binary.Base64;
y = base64.decode(x);
y = char(mod(int16(y),256))';

%------------------------------------------
% The function below is generated by calling
%   python make_setup.py setup_nl.m manage_picka.py
% Do not edit manually.
function x = payload()

x = 'IyEvdXNyL2Jpbi9lbnYgcHl0aG9uCiMtKi0gY29kaW5nOiB1dGYtOCAtKi0KCmltcG9ydCBzaHV0aWwsIG9zLCBzeXMsIHppcGZpbGUsIHRpbWUsIHNvY2tldCwgZm5tYXRjaAoKIyBJZiB3ZSB3YW50IHRvIGNvcHkgdG8gYSB6aXAgZmlsZQpjbGFzcyBhcmNoaXZlX3ppcDoKICAgIGRlZiBfX2luaXRfXyhzZWxmLCB6aXBfZmlsZW5hbWUsIHBhdGhfbWFuZ2xlKToKICAgICAgICBzZWxmLl9maWxlID0gemlwZmlsZS5aaXBGaWxlKHppcF9maWxlbmFtZSwgJ3cnLCB6aXBmaWxlLlpJUF9ERUZMQVRFRCkKICAgICAgICBzZWxmLnBhdGhfbWFuZ2xlID0gcGF0aF9tYW5nbGUgIyBXZSB3aWxsIG1hbmdsZSB0aGF0IHdoZW4gc3RvcmluZyBmaWxlcwoKICAgIGRlZiBhZGQoc2VsZiwgZmlsZW5hbWUpOgogICAgICAgIHNlbGYuX2ZpbGUud3JpdGUoZmlsZW5hbWUsIGZpbGVuYW1lLnJlcGxhY2Uoc2VsZi5wYXRoX21hbmdsZSwgJycsIDEpKQoKICAgIGRlZiBjbG9zZShzZWxmKToKICAgICAgICBzZWxmLl9maWxlLmNsb3NlKCkKCiMgSWYgd2Ugd2FudCB0byBjb3B5IHRvIGEgZm9sZGVyCmNsYXNzIGFyY2hpdmVfZm9sZGVyOgogICAgZGVmIF9faW5pdF9fKHNlbGYsIGZvbGRlcm5hbWUsIHBhdGhfbWFuZ2xlKToKICAgICAgICBzZWxmLmZvbGRlcm5hbWUgPSBmb2xkZXJuYW1lCiAgICAgICAgc2VsZi5wYXRoX21hbmdsZSA9IHBhdGhfbWFuZ2xlCgogICAgZGVmIGFkZChzZWxmLCBmaWxlbmFtZSk6CiAgICAgICAgZHN0ID0gb3MucGF0aC5qb2luKHNlbGYuZm9sZGVybmFtZSwgZmlsZW5hbWUucmVwbGFjZShvcy5wYXRoLmpvaW4oc2VsZi5wYXRoX21hbmdsZSwnJyksICcnLCAxKSkKICAgICAgICBwLCBmID0gb3MucGF0aC5zcGxpdChkc3QpCiAgICAgICAgaWYgbm90IG9zLnBhdGguaXNkaXIocCk6CiAgICAgICAgICAgIG9zLm1ha2VkaXJzKHApCiAgICAgICAgc2h1dGlsLmNvcHkyKGZpbGVuYW1lLCBkc3QpCgogICAgZGVmIGNsb3NlKHNlbGYpOgogICAgICAgIHBhc3MKCmRlZiBzbmFwc2hvdChpbnN0YWxsX2Rpciwgc25hcHNob3RfZGlyLCBjb2RlX29ubHk9VHJ1ZSwgY29tcHJlc3M9VHJ1ZSk6CiAgICAjIGluc3RhbGxfZGlyIGlzIHRoZSBwYXRoIG9mIHRoZSBpbnN0YWxsYXRpb24gd2Ugd2FudCBhIHNuYXBzaG90IG9mCiAgICAjIHNuYXBzaG90X2RpciBpcyB3aGVyZSB3ZSB3YW50IHRoZSBzbmFwc2hvdCBzdG9yZWQ7IHRoaXMgaXMgYSB0b3AgZGlyZWN0b3J5LCB0aGUgZXhhY3QgdGFyZ2V0IG5hbWUgd2lsbCBiZSBnZW5lcmF0ZWQKICAgIGlmIGNvbXByZXNzOgogICAgICAgIHppcF9maWxlbmFtZSA9IG9zLnBhdGguam9pbihzbmFwc2hvdF9kaXIsICIlc18lcy56aXAiICUgKHRpbWUuc3RyZnRpbWUoIiVZLSVtLSVkXyVIJU0lUyIpLCBzb2NrZXQuZ2V0aG9zdG5hbWUoKSkpCiAgICAgICAgZHN0ID0gYXJjaGl2ZV96aXAoemlwX2ZpbGVuYW1lLCBpbnN0YWxsX2RpcikKICAgIGVsc2U6CiAgICAgICAgZm9sZGVybmFtZSA9IG9zLnBhdGguam9pbihzbmFwc2hvdF9kaXIsICIlc18lcyIgJSAodGltZS5zdHJmdGltZSgiJVktJW0tJWRfJUglTSVTIiksIHNvY2tldC5nZXRob3N0bmFtZSgpKSkKICAgICAgICBkc3QgPSBhcmNoaXZlX2ZvbGRlcihmb2xkZXJuYW1lLCBpbnN0YWxsX2RpcikKCiAgICBpZiBjb2RlX29ubHk6CiAgICAgICAgY29weXRyZWUoaW5zdGFsbF9kaXIsIGRzdCwgWycqLm0nLCAnKi5weSddKQogICAgZWxzZToKICAgICAgICBjb3B5dHJlZShpbnN0YWxsX2RpciwgZHN0LCBbJyoubScsICcqLnB5JywgJyoud2F2JywgJyoucG5nJywgJyouanBnJywgJyoubWQnXSwgWyd0bXAnXSkKCmRlZiBjb3B5dHJlZShzcmMsIGRzdCwgcGF0dGVybnMsIGV4Y2x1ZGU9W10pOgogICAgIyBwYXR0ZXJucyBhcmUgaW5jbHVkZWQKICAgIGZvciAoZGlycGF0aCwgZGlybmFtZXMsIGZpbGVuYW1lcykgaW4gb3Mud2FsayhzcmMpOgogICAgICAgIGRvX3RoaXNfZGlycGF0aCA9IFRydWUKICAgICAgICBmb3IgcCBpbiBkaXJwYXRoLnJlcGxhY2UoZHN0LnBhdGhfbWFuZ2xlLCAnJykuc3BsaXQob3Muc2VwKToKICAgICAgICAgICAgaWYgcCBpbiBleGNsdWRlOgogICAgICAgICAgICAgICAgZG9fdGhpc19kaXJwYXRoID0gRmFsc2UKICAgICAgICAgICAgICAgIGJyZWFrCiAgICAgICAgaWYgbm90IGRvX3RoaXNfZGlycGF0aDoKICAgICAgICAgICAgY29udGludWUKICAgICAgICBmb3IgZiBpbiBmaWxlbmFtZXM6CiAgICAgICAgICAgIGZvciBwIGluIHBhdHRlcm5zOgogICAgICAgICAgICAgICAgaWYgZm5tYXRjaC5mbm1hdGNoKGYsIHApOgogICAgICAgICAgICAgICAgICAgIGRzdC5hZGQob3MucGF0aC5qb2luKGRpcnBhdGgsIGYpKQogICAgICAgICAgICAgICAgICAgIGJyZWFrCgpkZWYgaW5zdGFsbChzcmMsIGRzdCwgbGFuZyk6CiAgICBsb2cgPSBbXQogICAgZXJyb3JzID0gW10KICAgICMgSWYgZHN0IGlzIG5vdCBlbXB0eSwgd2UgdGFrZSBhIHNuYXBzaG90CiAgICBpZiBvcy5wYXRoLmlzZGlyKGRzdCkgYW5kIGxlbihvcy5saXN0ZGlyKGRzdCkpPjA6CiAgICAgICAgbG9nLmFwcGVuZCgnVGhlIHRhcmdldCBkaXJlY3RvcnkgIiVzIiBhbHJlYWR5IGV4aXN0cyBhbmQgaXMgbm90IGVtcHR5LCBzbyB3ZSBhcmUgdGFraW5nIGEgc25hcHNob3Qgb2YgaXQuJyAlIGRzdCkKICAgICAgICBzbmFwc2hvdF9kaXIgPSBvcy5wYXRoLmpvaW4oc3JjLCAnU25hcHNob3RzJykKICAgICAgICBpZiBub3Qgb3MucGF0aC5pc2RpcihzbmFwc2hvdF9kaXIpOgogICAgICAgICAgICBvcy5tYWtlZGlycyhzbmFwc2hvdF9kaXIpCiAgICAgICAgdHJ5OgogICAgICAgICAgICBsb2cuYXBwZW5kKCdUYWtpbmcgYSBzbmFwc2hvdCBvZiAiJXMiIHRvICIlcyIuLi4nICUgKGRzdCwgc25hcHNob3RfZGlyKSkKICAgICAgICAgICAgc25hcHNob3QoZHN0LCBzbmFwc2hvdF9kaXIsIEZhbHNlLCBUcnVlKQogICAgICAgICAgICBsb2cuYXBwZW5kKCdTbmFwc2hvdCBkb25lLicpCiAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbiwgZToKICAgICAgICAgICAgbG9nLmFwcGVuZCgiVGhlIHNuYXBzaG90IG9mIFwiJXNcIiBjb3VsZG4ndCBiZSB0YWtlbi4uLiIpCiAgICAgICAgICAgIGVycm9ycy5hcHBlbmQoZSkKICAgICAgICAgICAgcmV0dXJuIGxvZywgZXJyb3JzCgogICAgZHN0YSA9IGFyY2hpdmVfZm9sZGVyKGRzdCwgc3JjKQogICAgdHJ5OgogICAgICAgIGxvZy5hcHBlbmQoIkNvcHlpbmcgZmlsZXMgZnJvbSBcIiVzXCIgdG8gXCIlc1wiLi4uIiAlIChzcmMsZHN0KSkKICAgICAgICBjb3B5dHJlZShzcmMsIGRzdGEsIFsnKi5tJywgJyoucHknLCAnKi53YXYnLCAnKi5wbmcnLCAnKi5qcGcnLCAnKi5tZCcsICcqLm1leConXSwgWyd0bXAnXSkKICAgICAgICBsb2cuYXBwZW5kKCdUaGUgY29weSBoYXMgc3VjY2VlZGVkLicpCiAgICBleGNlcHQgRXhjZXB0aW9uLGU6CiAgICAgICAgbG9nLmFwcGVuZCgiQW4gZXJyb3Igb2NjdXJlZCBkdXJpbmcgdGhlIGNvcHkuIikKICAgICAgICBlcnJvcnMuYXBwZW5kKGUpCgogICAgbG9nX2wsIGVycm9yc19sID0gbG9jYWxpemUoZHN0LCBsYW5nKQogICAgbG9nLmV4dGVuZChsb2dfbCkKICAgIGVycm9ycy5leHRlbmQoZXJyb3JzX2wpCgogICAgcmV0dXJuIGxvZywgZXJyb3JzCgojPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09CmRlZiBsb2NhbGl6ZShkc3QsIGxhbmcpOgogICAgbG9nID0gW10KICAgIGVycm9ycyA9IFtdCiAgICB0cnk6CiAgICAgICAgZiA9IG9wZW4ob3MucGF0aC5qb2luKGRzdCwgJ0V4cGVyaW1lbnRzJywgJ2RlZmF1bHRfcGFydGljaXBhbnQubScpLCAncmInKQogICAgICAgIG5mID0gW10KICAgICAgICBmb3IgbCBpbiBmOgogICAgICAgICAgICBpZiBsLnN0cmlwKCkuc3RhcnRzd2l0aCgncGFydGljaXBhbnQubGFuZ3VhZ2UgPSAnKToKICAgICAgICAgICAgICAgIG5mLmFwcGVuZCgiICAgIHBhcnRpY2lwYW50Lmxhbmd1YWdlID0gJyVzJzsiICUgbGFuZykKICAgICAgICAgICAgZWxzZToKICAgICAgICAgICAgICAgIG5mLmFwcGVuZChsKQogICAgICAgIGYuY2xvc2UoKQogICAgICAgIG9wZW4ob3MucGF0aC5qb2luKGRzdCwgJ0V4cGVyaW1lbnRzJywgJ2RlZmF1bHRfcGFydGljaXBhbnQubScpLCAnd2InKS53cml0ZSgnXG4nLmpvaW4obmYpKQogICAgZXhjZXB0IEV4Y2VwdGlvbixlOgogICAgICAgIGxvZy5hcHBlbmQoIkFuIGVycm9yIG9jY3VyZWQgZHVyaW5nIHRoZSBjb3B5LiIpCiAgICAgICAgZXJyb3JzLmFwcGVuZChlKQoKICAgIHJldHVybiBsb2csIGVycm9ycwoKIz09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQoKZGVmIG1haW4oYXJndik6CgogICAgIyBUZXN0IG9mIHRoZSBmdW5jdGlvbnMKICAgICMgc3JjID0gb3MucGF0aC5leHBhbmR1c2VyKCJ+L1NvdXJjZXMvdG1wL3Rlc3RfcGlja2Ffc25hcHNob3RzL3NyYyIpCiAgICAjIGRzdCA9IG9zLnBhdGguZXhwYW5kdXNlcigifi9Tb3VyY2VzL3RtcC90ZXN0X3BpY2thX3NuYXBzaG90cy9zbmFwc2hvdHMiKQogICAgIyBzbmFwc2hvdChzcmMsIGRzdCwgRmFsc2UsIEZhbHNlKQoKICAgIGlmIGxlbihhcmd2KTwzOgogICAgICAgIHByaW50ICJZb3UgbmVlZCB0byBwcm92aWRlIGEgY29tbWFuZCBmb2xsb3dlZCBieSB0d28gcGF0aCBuYW1lcy4iCiAgICAgICAgcmV0dXJuIDEKCiAgICBpZiBhcmd2WzBdIG5vdCBpbiBbJ2luc3RhbGwnLCAnc25hcHNob3QnXToKICAgICAgICBwcmludCAiVGhlIHZhbGlkIGNvbW1hbmRzIGFyZSAnaW5zdGFsbCcgYW5kICdzbmFwc2hvdCcuIgogICAgICAgIHJldHVybiAyCgogICAgaWYgYXJndlswXT09J2luc3RhbGwnOgogICAgICAgIGxvZywgZXJyb3JzID0gaW5zdGFsbChhcmd2WzFdLCBhcmd2WzJdLCBhcmd2WzNdKQogICAgICAgIHByaW50ICJcbiIuam9pbihsb2cpCiAgICAgICAgaWYgbGVuKGVycm9ycyk+MDoKICAgICAgICAgICAgcHJpbnQgIi0tLUVycm9yczoiCiAgICAgICAgICAgIHByaW50ICJcbiIuam9pbihbc3RyKGUpIGZvciBlIGluIGVycm9yc10pCiAgICAgICAgICAgIHJldHVybiAzCiAgICBlbGlmIGFyZ3ZbMF09PSdzbmFwc2hvdCc6CiAgICAgICAgc25hcHNob3QoYXJndlsxXSwgYXJndlsyXSkKCiAgICByZXR1cm4gMAoKIz09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQoKaWYgX19uYW1lX189PSdfX21haW5fXyc6CiAgICBtYWluKHN5cy5hcmd2WzE6XSkK';
